# Generated by Django 4.2.7 on 2023-12-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_pais_origen'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
